#/usr/bin/env bash

# TODO:
#  make the script runnable from other diretories than the root
#  nextflow directory.

# default value for the run name
run_name="latest"
port="8080"
allowed_host=""

zdb_container="zdb:1.1"

# those parameters are mostly here for debugging purposes
zdb_folder="/home/chlamdb/"
metagenlab_folder=""
debug=false
use_dev_server=false


for i in "$@"; do
	case $i in
		--port=*)
			port="${i#*=}"
			shift
			;;
		--allowed_host=*)
			allowed_host="${i#*=}"
			shift
			;;
		--name=*)
			run_name="${i#*=}"
			shift
			;;
		-d|--debug)
			debug=true
			shift
			;;
		--dev_server)
			use_dev_server=true
			shift
			;;
		--zdb_folder=*)
			zdb_folder="${i#*=}"
			shift
			;;
		--metagenlab_folder=*)
			metagenlab_folder="${i#*=}"
			shift
			;;
		-h|--help)
			echo ""
			echo "This script starts the web application, using by default the database "
			echo "that was generated by the latest run of the annotation pipeline"
			echo ""
			echo "Arguments:"
			echo "--name=NAME: tells the web application to use a different database than the latest"
			echo "--port=PORT: the web server will listen on a different port (default: 8080)"
			echo "--allowed_host=HOSTS: coma separated list that will be passed as argument to django ALLOWED_HOSTS. If none specified, will try to guess with the hostname command. This is basically the URL or IP adress you will using to access the web page."
			echo ""
			exit 0
			;;
		*)
			echo "Unknown option $i"
			exit 1
	esac
done


if [ ! -f "singularity/${zdb_container}.sif" ]; then
	echo "Preparing the zdb container, this may take a while."
	singularity build singularity/${zdb_container}.sif docker://registry.hub.docker.com/metagenlab/${zdb_container} &> singularity_log
	if [ ! $? -eq 0 ]; then
		echo "Failed to download singularity, more information in the singularity_log file"
		exit 1
	else
		rm singularity_log
	fi
	echo "Done"
fi

gunicorn_dir="zdb/gunicorn/"
nginx_dir="zdb/nginx"

debugging_mode=""
bind_path="zdb/assets/:${zdb_folder}/assets/temp/,${gunicorn_dir}:/usr/local/gunicorn/"
bind_path="$bind_path,${nginx_dir}:/usr/local/nginx"


if [ "$debug" = true ]; then
	debugging_mode="-d"
fi

if [ ! -d "zdb/nginx/var" ]; then
	mkdir zdb/nginx/var
fi

if [ ! -d "zdb/assets" ]; then
	mkdir zdb/assets
fi

if [ ! -z "${metagenlab_folder}" ]; then
	bind_path="${bind_path},${metagenlab_folder}"
	export PYTHONPATH="$metagenlab_folder"
fi

if [ ! -z "${allowed_host}" ]; then
	allowed_host="--host=${allowed_host}"
fi

dev_server=""
if [ "$use_dev_server" = true ]; then
	dev_server="--use_dev_server"
	debugging_mode="-d"
fi


# De-alias the run_name
if [ -f "zdb/results/.completed_runs/${run_name}" ]; then
	run_name=$(cat zdb/results/.completed_runs/${run_name})
else
	echo "The following complete run are available:"
	echo ""
	for i in $(ls zdb/results/.completed_runs); do
		if [ "$(cat zdb/results/.completed_runs/$i)" = "$i" ]; then
			echo $i
		else
			echo "$i -> $(cat zdb/results/.completed_runs/$i)"
		fi
	done

	echo ""
	echo "No run with name : ${run_name}"
	exit 1
fi


# NOTE: as some of these files may be symbolic links (particularly if using latest)
# zdb relies on this script being run from the nextflow directory so that singularity
# mounts the whole results dir in the container and keep the symbolic links valid

bind_path="${bind_path},zdb/results/db/${run_name}:${zdb_folder}/assets/db/${run_name}"
bind_path="${bind_path},zdb/results/search_index/${run_name}:${zdb_folder}/assets/search_index/${run_name}"
bind_path="${bind_path},zdb/results/blast_DB/${run_name}:${zdb_folder}/assets/blast_DB/${run_name}"
bind_path="${bind_path},zdb/results/alignments/${run_name}:${zdb_folder}/assets/alignments/"

# annoying part to avoid error messages from nginx attempting to write
# into an hard-coded /var/log/nginx/error.log -> the zdb/nginx/var directory is mounted
# on /var/log/nginx in the container so that nginx can write in the file and be happy.

bind_path="${bind_path},zdb/nginx/var:/var/log/nginx"


# To be added later, to allow users to download the newick trees
# bind_path="${bind_path},zdb/results/gene_phylogenies/${run_name}:${zdb_folder}/assets/phylogenies/"

singularity run --writable-tmpfs --bind ${bind_path} \
	singularity/${zdb_container}.sif ${zdb_folder}/start_webapp \
	--run_name=${run_name} --port=${port} ${debugging_mode} ${allowed_host} ${dev_server}


