#/usr/bin/env bash

# default value for the run name
run_name="latest"
port="8080"

for i in "$@"; do
	case $i in
		--port=*)
			shift
			;;
		--run_name=*)
			run_name="${i#*=}"
			shift
			;;
		-h|--help)
			echo ""
			echo "This script starts the web applcation, using by default the database "
			echo "that was generated by the latest run of the annotation pipeline"
			echo ""
			echo "Arguments:"
			echo "--run_name=NAME: tells the web application to use a different database than the latest"
			echo "--port=PORT: the web server will listen on a different port (default: 8080)"
			echo ""
			exit 0
	esac
done

if [ ! -f "singularity/chlamdb-latest.sif" ]; then
	echo "Preparing the chlamdb container, this may take a while."
	singularity build singularity/chlamdb-latest.sif docker-daemon://metagenlab/chlamdb:latest
	echo "Done"
fi


export RUN_NAME="$run_name"
export PORT="$port"
export NEXTFLOW_DIR=`pwd`
echo "Starting website, it will be accessible through on localhost on port $port"
singularity run --writable-tmpfs --bind tmp/:/home/chlamdb/assets/temp/ \
	singularity/chlamdb-latest.sif /home/chlamdb/start_webapp
