#/usr/bin/env bash

# default value for the run name
run_name="latest"
port="8080"
allowed_host=""

zdb_container="zdb:1.1"

# those parameters are mostly here for debugging purposes
zdb_folder=""
metagenlab_folder=""
debug=false
use_dev_server=false


for i in "$@"; do
	case $i in
		--port=*)
			port="${i#*=}"
			shift
			;;
		--allowed_host=*)
			allowed_host="${i#*=}"
			shift
			;;
		--run_name=*)
			run_name="${i#*=}"
			shift
			;;
		-d|--debug)
			debug=true
			shift
			;;
		--dev_server)
			use_dev_server=true
			shift
			;;
		--zdb_folder=*)
			zdb_folder="${i#*=}"
			shift
			;;
		--metagenlab_folder=*)
			metagenlab_folder="${i#*=}"
			shift
			;;
		-h|--help)
			echo ""
			echo "This script starts the web application, using by default the database "
			echo "that was generated by the latest run of the annotation pipeline"
			echo ""
			echo "Arguments:"
			echo "--run_name=NAME: tells the web application to use a different database than the latest"
			echo "--port=PORT: the web server will listen on a different port (default: 8080)"
			echo "--allowed_host=HOSTS: coma separated list that will be passed as argument to django ALLOWED_HOSTS. If none specified, will try to guess with the hostname command. This is basically the URL or IP adress you will using to access the web page."
			echo ""
			exit 0
			;;
		*)
			echo "Unknown option $i"
			exit 1
	esac
done


if [ ! -f "singularity/${zdb_container}.sif" ]; then
	echo "Preparing the zdb container, this may take a while."
	singularity build singularity/${zdb_container}.sif docker://registry.hub.docker.com/metagenlab/${zdb_container} &> singularity_log
	if [ ! $? -eq 0 ]; then
		echo "Failed to download singularity, more information in the singularity_log file"
		exit 1
	else
		rm singularity_log
	fi
	echo "Done"
fi

nextflow_dir=`pwd`
zdb_home="/home/chlamdb/"
debugging_mode=""
bind_path="tmp/:/home/chlamdb/assets/temp/"

if [ "$debug" = true ]; then
	debugging_mode="-d"
fi

if [ ! -z "${zdb_folder}" ]; then
	zdb_home="${zdb_folder}"
	bind_path="tmp/:${zdb_folder}/assets/temp/"
fi

if [ ! -z "${metagenlab_folder}" ]; then
	bind_path="${bind_path},${metagenlab_folder}"
	export PYTHONPATH="$metagenlab_folder"
fi

if [ ! -z "${allowed_host}" ]; then
	allowed_host="--host=${allowed_host}"
fi

dev_server=""
echo $use_dev_server
if [ "$use_dev_server" = true ]; then
	dev_server="--use_dev_server"
fi


echo "Starting website, it will be accessible through on localhost on port $port"
singularity run --writable-tmpfs --bind ${bind_path} \
	singularity/${zdb_container}.sif ${zdb_home}/start_webapp --nextflow_dir="${nextflow_dir}" \
	--run_name=${run_name} --port=${port} ${debugging_mode} ${allowed_host} ${dev_server}
