{% set version = "1.1.1" %}

package:
  name: zdb
  version: {{ version }}

build:
  noarch: generic
  number: 9

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.1.1.tar.gz
  sha256: 37307fe27cd0ca3b65fc1ce1a1c7727ee77e692ab671b8b78af6a0ff3f09e2b6

requirements:
  run:
    - nextflow >=21.04.0,<=22.10.8

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
