{% set version = "1.0.8" %}

package:
  name: zdb
  version: {{ version }}

build:
  number: 5

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.0.8-beta.tar.gz
  sha256: bf69cf86bc6053693d67706ef8ecb5ddc2ebbcec9af0cbf8f4489f62c5e50abe

requirements:
  run:
    - nextflow >=21.04.0

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
