{% set version = "1.2.0" %}

package:
  name: zdb
  version: {{ version }}

build:
  noarch: generic
  number: 0

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.2.0.tar.gz
  sha256: 19611b62cf591f03697259748e9aae8d8f82541885879d2f3a8c3d69e9bb72ab

requirements:
  run:
    - nextflow >=21.04.0,<=22.10.8
    - mamba

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
