{% set version = "1.0.8" %}

package:
  name: zdb
  version: {{ version }}

build:
  number: 4

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.0.8-beta.tar.gz
  sha256: d292a7774c8fec45515de8bd0b1b457100f4c9a186e74656c4a670131de5050d

requirements:
  run:
    - nextflow >=21.04.0

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
