{% set version = "1.1.1" %}

package:
  name: zdb
  version: {{ version }}

build:
  noarch: generic
  number: 8

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.1.1.tar.gz
  sha256: 66b4696a248222e06a0d82f25ba28c14f2a96af3598d71e8dd632142aff714d4

requirements:
  run:
    - nextflow >=21.04.0,<=22.10.8

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
