{% set version = "1.0.8" %}

package:
  name: zdb
  version: {{ version }}

build:
  number: 4

source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.0.8-beta.tar.gz
  sha256: bb2d604c3f67a1927d49fa08d387f4a3726554aeb3baccea224c91c8f47974c1

requirements:
  run:
    - nextflow >=21.04.0

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
