#!/bin/bash
# NEXTFLOW TASK: rpsblast_COG (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_date() {
    local ts=$(date +%s%3N); [[ $ts == *3N ]] && date +%s000 || echo $ts
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /scratch/hdd/bmarquis/annotation_pipeline_nextflow/work/62/742bb9cfeb402ea3086bb540edb634/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /scratch/hdd/bmarquis/annotation_pipeline_nextflow/work/62/742bb9cfeb402ea3086bb540edb634/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f seq
    ln -s /scratch/hdd/bmarquis/annotation_pipeline_nextflow/work/84/5dc9f27d929cd01c7aab02cec6494b/chunk_.1 seq
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /scratch/hdd/bmarquis/annotation_pipeline_nextflow/work/62/742bb9cfeb402ea3086bb540edb634/.command.begin
    set +u
    set -u
    export HMMTOP_ARCH="/home/tpillone/work/dev/annotation_pipeline_nextflow/bin/hmmtop_2.1/hmmtop.arch"
    export HMMTOP_PSV="/home/tpillone/work/dev/annotation_pipeline_nextflow/bin/hmmtop_2.1/hmmtop.psv"
    export INTERPRO_HOME="/home/tpillone/work/projets/dev/2018_11_annotation_pipeline/databases/interproscan/interproscan-5.34-73.0"
    export HMMTOP_PATH="/home/tpillone/work/dev/annotation_pipeline_nextflow/bin/hmmtop_2.1"
    export GBLAST3_PATH="/home/tpillone/work/dev/annotation_pipeline_nextflow/bin/BioVx/scripts"
    export KOFAMSCAN_HOME="/home/tpillone/work/dev/annotation_pipeline_nextflow/bin/KofamScan/"
    export PYTHONPATH="/scratch/hdd/bmarquis/annotation_pipeline_nextflow/bin"
    export PATH="/scratch/hdd/bmarquis/annotation_pipeline_nextflow/bin:$PATH"
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
